feat: 🎸 Filter out moving time window seeds in subject list
chatatechnologies/react-autoql pull request #500
Opened 2022-10-13 19:49 UTC by alexzhou-chata

Filter out moving time window seeds in subject list

✅ Closes: AC-2414

2022-10-13 19:52 UTC, AlexLiu-Chata approved these changes

2022-10-13 19:56 UTC, NikkiMeganMoore requested changes

2022-10-13 19:56 UTC, NikkiMeganMoore commented on src/components/DataExplorer/DataExplorerInput.js
> +  isNotAggSeed(subject) {
Usually you want to make these "affirmative" so `isAggSeed` then if you want to negate them just do `!isAggSeed` I find it much easier to read

2022-10-13 20:11 UTC, NikkiMeganMoore approved these changes

2022-10-13 20:13 UTC, merged

2022-10-18 22:50 UTC, NikkiMeganMoore commented
:tada: This PR is included in version 6.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-autoql/v/6.1.0)
- [GitHub release](https://github.com/chatatechnologies/react-autoql/releases/tag/v6.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: