Ac 2480
chatatechnologies/react-autoql pull request #535
Opened 2022-11-15 18:43 UTC by alexzhou-chata

2022-11-15 19:05 UTC, AlexLiu-Chata submitted a review, later dismissed

2022-11-15 19:13 UTC, NikkiMeganMoore requested changes

2022-11-15 19:13 UTC, NikkiMeganMoore commented on src/components/QueryOutput/QueryOutput.js
> +    const footerClassName =
This seems a bit confusing to me. What if we did something like this

```
const footerClassName =
    `query-output-footer-top
    ${!shouldRenderRT ? 'no-margin' : ''}
    ${this.props.reverseTranslationPlacement}`
```

Then the css selector could just be

`.query-output-footer.top` or `.query-output-footer.bottom`

2022-11-15 20:05 UTC, NikkiMeganMoore approved these changes

2022-11-15 20:07 UTC, merged

2022-11-23 20:28 UTC, NikkiMeganMoore commented
:tada: This PR is included in version 6.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-autoql/v/6.5.0)
- [GitHub release](https://github.com/chatatechnologies/react-autoql/releases/tag/v6.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: